### ISSUE TITLE
when I try to configure the SSD through AXI BAR, I cannot write to it. 

### ISSUE THREAD

**Issue by ztc6** [fpgadeveloper/fpga-drive-aximm-pcie#14]
Hello, we clone repo with project for Vivado 2019.2, but when I try to configure the SSD through AXI BAR, I cannot write to it. Bridge Enable has been turned on.Do you know what happened? Is the gen3 porting gen2 driver not supporting BAR?

**Comment by fpgadeveloper** [comment]
For this issue, please request support here: https://opsero.com/contact-us/
