### ISSUE TITLE
The IP is set as GEN3 x4, but the connection is trained as GEN1 X2.

### ISSUE THREAD

**Issue by ztc6** [fpgadeveloper/fpga-drive-aximm-pcie#15]
Hello, I am running this project on KCU105, the IP is set as GEN3 x4, but the connection is trained as GEN1 X2, may I ask what is wrong?
[]([]([]([](![1630636398(1)](https://user-images.githubusercontent.com/65806594/131941850-99749885-3ab3-41c8-af99-063a30eaf9e1.jpg)))))

**Comment by fpgadeveloper** [comment]
This issue most likely due to your particular hardware setup. Please ask for support here: https://opsero.com/contact-us/
