### ISSUE TITLE
[ZCU106] Boot stalls without proper connection with the FMC extension card

### ISSUE THREAD

**Issue by CaglayanDokme** [fpgadeveloper/fpga-drive-aximm-pcie#18]
I successfully generate the _.bit_ and _.hdf_ files and import them from the PetaLinux tool. Inside the Petalinux, I activate the required kernel modules-drivers for the PCIe and NVMe. Also for the rootfs, to monitor the devices I include some packages such as _lspci_, _lsblk_, _mount_, etc. 

The board boots up successfully if I connect the extension card to the FMC connector. _(I can't detect(lspci) the SSDs, but it's another problem.)_ But, somehow, the boot process stalls if I don't connect the extension card. A few seconds after powering up, the boot process stalls and prints the following message to the serial console:

> INFO: rcu_sched detected stalls on CPUs/tasks:

Luckily, I managed to detect the driver causing the stall. It was the **XDMA PL PCIe** driver. If I don't include the XDMA driver in the kernel, the board successfully boots up regardless of the existence of the extension card.

What would be the reason for it? Is there a problem with the PL design, or is it not even a problem at all?

**Comment by fpgadeveloper** [comment]
Hi,
You should not manually activate the required kernel modules/drivers. It is done by the build-petalinux script.
For more support on this, please use the Opsero contact form.
Jeff
