### ISSUE TITLE
VCU118 dual. no enumeration over bars

### ISSUE THREAD

**Issue by ecoding** [fpgadeveloper/fpga-drive-aximm-pcie#29]
Dear Mr. Johnson,

our setup in my student research project consists of a VCU118 FPGA in combination with the FPGA Drive Gen4, 1x Samsung 950 PRO SSD (256 GB) and 2x Samsung 980 PRO SSD (500GB).
We built the VCU118 dual Vitis project and run it on the VCU118.
I managed to receive Uart output similiar to the reference from the documented xdma designs output (see: https://refdesign.fpgadrive.com/en/latest/stand_alone.html#output-of-xdma-designs).

What confuses me is that our output stops at `xdma_pcie: This is an End Point`, and the program got stuck.
We are missing the following lines in our output:
```
xdma_pcie: bus: 1, device: 0, function: 0: BAR 0, ADDR: 0xA0000000 size : 16K
xdma_pcie: bus: 1, device: 0, function: 0: BAR 2 is not implemented
xdma_pcie: bus: 1, device: 0, function: 0: BAR 3 is not implemented
xdma_pcie: bus: 1, device: 0, function: 0: BAR 4 is not implemented
xdma_pcie: bus: 1, device: 0, function: 0: BAR 5 is not implemented
xdma_pcie: End Point has been enabled
Successfully ran XdmaPcie rc enumerate Example
```
Is it due to the fact that we are not using two PCIe 3.0 ssds of the same kind?

Sincerely
ecoding

**Comment by fpgadeveloper** [comment]
Hi ecoding,

Please send us a request for support here: https://opsero.com/contact-us/

Jeff
