### ISSUE TITLE
S_AXI_LITE's assigned address is out of range

### ISSUE THREAD

**Issue by yu-zou** [fpgadeveloper/fpga-drive-aximm-pcie#6]
![image](https://user-images.githubusercontent.com/11840520/80560179-00dcb300-89ae-11ea-966a-f73e0e3b8a68.png)
As shown the CTRL0 address was assigned to 0x04_0000_0000.
However, the S_AXI_LITE address channel is 32-bit, which is incompatible with assigned address.
![image](https://user-images.githubusercontent.com/11840520/80560238-32ee1500-89ae-11ea-9ec0-50ad16669f48.png)

**Comment by fpgadeveloper** [comment]
A 32-bit AXI-lite interface can be assigned a 40-bit address as we have done in this design. If you find any documentation to the contrary, please post a link here. If you have a warning message from the Vivado tool, please post it here.

**Comment by yu-zou** [comment]
That's a stupid question. Never mind.
