### ISSUE TITLE
Need help with simulation of fpga-drive-aximm-pcie-2018.2_1 on vivado

### ISSUE THREAD

**Issue by jdlr-at-nrec** [fpgadeveloper/fpga-drive-aximm-pcie#9]
Is this the correct place to ask?

Jaime

**Comment by fpgadeveloper** [comment]
Unfortunately we haven't got a testbench for simulating this design and you're the first person to ask about it. If you find your own testbench file I'd be happy to accept a PR and add it to the design.
Jeff

**Comment by jdlr-at-nrec** [comment]
If i manage to come up with something, you’ll be the first one, i’ll share it with.

Jaime
